name: Retrain ML Model with MLflow Project

on:
  workflow_dispatch: 
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow-CI repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies (conda)
        run: |
          python -m pip install --upgrade pip
          # Karena MLProject Anda menggunakan conda.yaml (yang diasumsikan akan diurus oleh mlflow run),
          # dan Anda menginstal pandas, numpy, scikit-learn secara global,
          # ini mungkin tidak optimal jika ada konflik lingkungan.
          # Untuk saat ini, biarkan seperti ini, tapi perlu diingat.
          pip install mlflow scikit-learn pandas numpy matplotlib

      - name: Run MLflow project # <-- Perbaikan ada di sini
        run: |
          # Perintah ini sekarang menjalankan MLflow Project dari sub-direktori 'MLProject'
          mlflow run MLProject --env-manager=local # <-- UBAH DARI '.' MENJADI 'MLProject'

      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          # Jika mlflow run MLProject dijalankan, maka folder mlruns akan dibuat di dalam 'MLProject'.
          path: MLProject/mlruns # <-- SESUAIKAN PATH ARTIFAK