name: Retrain ML Model with MLflow Project

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12 (with Conda) 
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Conda Init and Setup 
        shell: bash -l {0} 
        run: |
          conda update -n base -c defaults conda --yes
          conda clean --all --yes
          conda config --set channel_priority strict
          echo "Conda version: $(conda --version)" # Debugging: cek versi conda

      - name: Install MLflow Project dependencies 
        run: |
          cd ./MLproject
          conda env create -f conda.yaml 
          pip install mlflow 

      - name: Run MLflow project
        run: |
          mlflow run MLproject --env-manager=local 

      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: MLproject/mlruns 